services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres-agiota
    restart: always
    environment:
      POSTGRES_USER: agiota
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432